  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: myfirstpythonapp
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: myfirstpythonapp
    template:
      metadata:
        labels:
          app: myfirstpythonapp
      spec:
        containers:
        - name: myfirstpythonapp
          image: princessujay/myfirstpythonapp:0.0.1.RELEASE
          ports:
          - containerPort: 8000
          env:
          - name: WELCOME_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: WELCOME_MESSAGE
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: SECRET_PASSWORD
